### ISSUE TITLE
NOTE: .gitignore file doesn't work

### ISSUE THREAD

**Issue by loss4Wang** [loss4Wang/cs61a-learning#1]
Cause .gitignore file won't ignore files that have been **added to the Stage** yet 😂

**Comment by MarioZZJ** [comment]
maybe rename it to `.gitignore` and add * to the contents might work:)
I suggest reinit the local git repo and push to Github again.

**Comment by loss4Wang** [comment]
> maybe rename it to `.gitignore` and add * to the contents might work:)
> I suggest reinit the local git repo and push to Github again.

Thanks a lot for your quick help, I think a hw2 is nothing too sensitive to push to the Github repo XD

**Comment by loss4Wang** [comment]
AOGE NB!
